---
title: "Skyine Analysis- Biochar Experiment"
author: "Peter Levy"
output:
  html_document:
    number_sections: yes
    toc: no
  pdf_document:
    number_sections: yes
    toc: no
---

```{r render, echo = FALSE, eval = FALSE}
here::i_am("analysis/skyline_analysis_diurnal.Rmd")
#renv::install("ggeffects")
library(here)
library(quarto)
library(rmarkdown)
quarto_render(here("analysis/skyline_analysis_diurnal.Rmd"))
render(input = here("analysis", "skyline_analysis_diurnal.Rmd"), output_file = here("analysis", "skyline_analysis_diurnal.pdf"))
render(input = here("analysis", "skyline_analysis_diurnal.Rmd"), output_file = here("analysis", "skyline_analysis_diurnal.html"))
```

Some provisional results from analysis of skyline data from DIVINE and ASSIST projects.

<!--- { startup -->
```{r startup, eval=TRUE, echo=FALSE, include=FALSE}
here::i_am("analysis/skyline_analysis_diurnal.Rmd")
library(here)
library(targets)
library(ggplot2)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,
  results = "hold", fig.show = "hold")
Sys.setenv(TAR_PROJECT = "diurnal")
```

# Diurnal variation

```{r, results = "hold", fig.show = "hold", echo = FALSE, fig.cap = "Diurnal variation in CO2 flux, N2O flux, PPFD and air temperature, averaged over all experiments."}
tar_read(p_diurnal_lumped, store = here("_targets_diurnal"))
```

```{r, results = "hold", fig.show = "hold", echo = FALSE, fig.cap = "Diurnal variation in CO2 flux, N2O flux, PPFD and air temperature, averaged separately for each experiment"}
tar_read(p_diurnal_by_expt, store = here("_targets_diurnal"))
```

```{r, results = "hold", fig.show = "hold", echo = FALSE, fig.cap = "Diurnal variation in CO2 flux, N2O flux, PPFD and air temperature, averaged separately for each day. Separating by each day gives equal weight to days with little variation, so shows relative variation rather than absolute variation."}
tar_read(p_diurnal_by_day, store = here("_targets_diurnal"))
```

```{r, results = "hold", fig.show = "hold", echo = FALSE, fig.cap = "Diurnal variation in CO2 flux, N2O flux, PPFD and air temperature, averaged separately for each experiment and for each day but pooling all chambers within an experiment and day. Separating by each experiment and day gives equal weight to both experiment and days with little variation, so shows relative variation rather than absolute variation."}
tar_read(p_diurnal_by_day_by_expt_not_chamber, store = here("_targets_diurnal"))
```

```{r, results = "hold", fig.show = "hold", echo = FALSE, fig.cap = "Diurnal variation in CO2 flux, N2O flux, PPFD and air temperature, averaged separately for each experiment and for each chamber on each day. Separating by each experiment and day gives equal weight to both experiment and days with little variation, so shows relative variation rather than absolute variation."}
tar_read(p_diurnal_by_day_by_expt_by_chamber, store = here("_targets_diurnal"))
```
